neomys is an ergonomic keyboard designed to be used with the Neo2 ergonomic keyboard layout.

These objectives have been taken into account in the neomys design:

* Split keyboard
neomys has not only a split key field (as e.g. the Microsoft Natural Ergonomic Keyboard), it is split into two separate parts which you can arrange in whatever position feels most comfortable for your hands (similar as with the ErgoDox.)

* Ergonomic key arrangement
neomys arranges the keys in a way that they are easy to reach with the according fingers when 10-finger touch typing: All keys associated with one finger are in one line (as also done with the TypeMatrix keyboard), and the keys to operate with the middle finger is located higher than the keys to operate with the much shorten pinky (similar as with the TECK, the ErgoDox and the Key64 Keyboard). The leftmost and rightmost key columns are slightly tilted to make them easier accessible (a bit like with the Kinesis Contoured Keyboard).

* Neo2 based
neomys is based on the Neo2 ergonomic keyboard layout. Neo2 is an ergonomic keyboard layout like the Dvorak, but optimized for the German language and modern computer keyboard usage. This brings several benefits over other (mostly QWERTY/Z-based) ergonomic keyboards.

** Fewer leaving the typing position
The Neo2 layout offers basically all keys you need regularly (Return, arrow keys, Home/End, Backspace/Delete, ...) easily reachable from the 10-finger touch typing position. This way, you can operate your computer with much less need to leave the typing position.
You will even need to use the top row (with all the numbers on it) only rarely, so every finger has to operate only very few keys regularly.

** Less keys
The neomys leaves out all keys you would have to leave the typing position for to reach and provides (basically) all keys of a regular 105-key ISO keyboard on less than 63 keys. (Similar as does the Key64 Keyboard, but with even less keys :) .) 

** "Portable" layout
As Neo2 drivers are available to use the Neo2 layout on all common operating systems (Windows, Linux/Unix, Mac, and there is something for Android as well[fn:1]) you can easily use a keyboard layout very close to the one you get used to when using the neomys on basically any other keyboard/computer you need to work with.

* Easy to switch between keyboards
In addition to the "portabiliy" benefits from using the Neo2 layout, the positions of the keys are kept very close to their positions on regular keyboards (esp. with the space, Ctrl/Strg, Win/Apple, Alt and these keys) as long as that position is not too bad for ergonomics. This faciliates switching from the neomys back to a regular keyboard when using your Laptop or another person's computer. If you have the Neo2 layout available on that computer (which should be easy with your laptop and managable with most other-person's computers you use frequently), it will be fairly easy to switch.
There are no keys you operate with the one finger on the neomys, and with a completely other finger on a regular keyboard (as it is with may keys on the TECK, the ErgoDox, the Key64 Keyboard or the Kinesis Contoured Keyboard).

* Emulate Neo2 on other layouts
The neomys firmware is pretty smart: It allows you to emulate the Neo2 layout on a number of other keyboard layouts. If you connect the neomys to a PC that only knows the QWERTZ layout, the neomys firmware will hide all modifier keys used to select the Neo2 levels (except for Shift) from the computer it is connected to and will translate any keypress on the neomys keyboard from the Neo2 layout to the keypress that has the desired effect on the computer. E.g.:
- The Y key of the QWERTY layout is the Z key in a QWERTZ layout and is the K key in the Neo2 layout. When in the Neo layout pressed together with the Mod3 key, it will cheate the '!' character. When you connect the neomys to a computer using the Neo2 layout, and press Mod3+K, neomys will tell the computer you pressed Mod3+K. (Sounds reasonable, huh? But now comes the funny part:) When you connect the neomys to a computer using the QWERTY or QWERTZ layout, and press Mod3+K, neomys will tell the computer you pressed Shift+1.
- The E key of the QWERTY/Z layout is the L key in the Neo2 layout. When in the Neo layout pressed together with the Mod3 key, it will cheate the '[' character. When you connect the neomys to a computer using the Neo2 layout, and press Mod3+L, neomys will tell the computer you pressed -- guess what? -- Mod3+L. When you connect the neomys to a PC using the US-ANSI QWERTY layout, it will tell you pressed the '[' key (which US-ANSI QWERTY keyboards have). When you connect the neomys to a PC using the (DIN 2137:2012-06 T1) QWERTZ layout, and press Mod3+L, neomys will tell the computer you pressed AltGr+8. When you connect the neomys to a Mac using the German Apple QWERTZ layout, and press Mod3+L, neomys will tell the computer you pressed Option+5. 

AFAIK, there is currently no other keyboard out there that can do such :) .

* Open development
As most of the Neo2 stuff and many of the keyboard projects I got inspired by, all of the neomys stuff I created is "Open Source" and released under GPLv3 or CC-BY-AT license. This way, anyone willing can build its own neomys keyboard (prototype for about 100€ and in one weekend, if you can buy your keyboard switches cheap and have some skills in electronics) free of charge and also participate in its development.

* Planned Features

** Operate the mouse from typing position
This is a feature planned for the next version of the neomys keyboard: The right Mod3 key shall be combined with a pointing stick[fn:2] mouse device, some keys can be used to do mouse clicks[fn:A]. The planned mouse integration is why I chose the name 'neomys' :) .

* Comparison to other ergonomic keyboards
The thing which distinguishes the neomys keyboard probably the most from the other ergonomic keyboards I know is the fact that it is designed with a specific ergonomic keyboard layout in mind, and that this layout already provides positions 


The thing which distinguishes the neomys keyboard probably the most from the other ergonomic keyboards I know is the fact that it leaves out separate keys for all those 'control and navigation' keys -- Return, arrow keys, Home/End, Backspace/Delete etc. As the Neo2 layout does it, all those keys are available from another level of the regular letter keys. With most other ergonomic keyboards, these keys are placed somewhere at the edge of the keyfield, and with some keyboards, the thumb has to operate many of these keys. With the Neo2 layout, you can easily use those keys with your fingers without having to leave the touch typing position and the number of keys can be reduced. The less keys, the easier it is to put all of them to positions you can easiliy reach with your fingers.

The 



is designed with a specific ergonomic keyboard layout in mind. Many of the ergonomic designs out there are designed with QWERTY in mind -- or at least support using them with the QWERTY layout. As such, they need to provide all these non-letter keys you need regularly when typing somewhere -- Return, arrow keys, Home/End, Backspace/Delete etc. Most of the time these keys are not to easy to reach from the touch typing home postition, or you have half a dozen of keys which you need to operate with your thumb, or both. On the neomys, these keys are located as Neo2 does it: in another level of the regular letter keys you use from the touch typing position. This way, no separate keys are needed for those 'control and navigation' keys, and as you have fewer keys, reaching all keys becomes easier.


[fn:A] The neomys has one keyboard layer in addition to those from the Neo2 layout. The lefthand side of that layer is very similar to Neo2 layer 4 (but provides function keys (F1--F5) on the number row), the righthand side is unrelated to Neo2 and specific to neomys and offers some additional keys to have substitutes for all keys from a full 105-key keyboard (F6-F12, Print Screen/Druck, Pause, ...) and for some other handy keys (Cut/Copy/Paste, Redo/Undo, ...) and shall offer keys to trigger mouse clicks.

[fn:1] http://github.com/thilo-fischer/neo2_on_android/blob/master/ABOUT
[fn:2] http://en.wikipedia.org/wiki/Pointing_stick
